name: Build binaries for Linux
on:
  workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          ./bin/micromamba create -r ~/micromamba -n py38 -c conda-forge python=3.8 --yes
          ./bin/micromamba run -r ~/micromamba -n py38 pip install pyinstaller
          ./bin/micromamba run -r ~/micromamba -n py38 pip install -r src/requirements.txt
          ./bin/micromamba run -r ~/micromamba -n py38 pyinstaller -F src/JSONConvert.py

      - name: Set release date
        run: echo "RELEASE_DATE=$(date -u +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_DATE }}
          release_name: Release ${{ env.RELEASE_DATE }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/JSONConvert
          asset_name: JSONConvert
          asset_content_type: application/octet-stream
