name: Build binaries for Linux & Windows
on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    # container: ubuntu:18.04
    # steps:
    #   - uses: actions/checkout@v3
    #   - run: |
    #       apt update && apt install wget tar binutils --yes
    #       wget https://github.com/indygreg/python-build-standalone/releases/download/20230116/cpython-3.8.16+20230116-x86_64-unknown-linux-gnu-install_only.tar.gz && \
    #       tar xf cpython-3.8.16+20230116-x86_64-unknown-linux-gnu-install_only.tar.gz && \
    #       ./python/bin/python3.8 -m pip install -r requirements.txt && \
    #       ./python/bin/python3.8 -m PyInstaller -F src/JSONConvert.py
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          ./bin/micromamba create -r ~/micromamba -n py38 -c conda-forge python=3.8 --yes
          ./bin/micromamba run -r ~/micromamba -n py38 pip install pyinstaller
          ./bin/micromamba run -r ~/micromamba -n py38 pip install -r requirements.txt
          ./bin/micromamba run -r ~/micromamba -n py38 pyinstaller -F src/JSONConvert.py

      - name: Set release date
        run: echo "RELEASE_DATE=$(date -u +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_DATE }}
          tag:  ${{ env.RELEASE_DATE }}
          artifacts: "dist/JSONConvert"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          draft: true


  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          python -m pip install -r requirements.txt
          python -m PyInstaller -F src/JSONConvert.py
      - name: Set release date
        shell: bash
        run: echo "RELEASE_DATE=$(date -u +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_DATE }}
          tag:  ${{ env.RELEASE_DATE }}
          artifacts: "dist/JSONConvert.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          draft: true
